//
//  HealthDetailModels.swift
//  CleanSwiftUI
//
//  Created by Siradanai.s on 2/7/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum HealthDetail {
    typealias SceneViewModel = HealthDetailSceneViewModel

    enum FetchDetail {
        struct Request {}

        struct Response {
            let recordType: HealthRecordType
            let records: [HealthRecord]
        }

        struct ViewModel {
            let unit: String
            let state: SceneViewModel.State
        }
    }
    
    enum SubmitRecord {
        struct Request {
            let value: Double
            let date: Date
            let mode: HealthInputForm.SceneOption
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            let records: [HealthRecordViewModel]
        }
    }
    
    enum RemoveDetail {
        struct Request {
            let record: HealthRecord
        }
        
        struct Response {  
        }
        
        struct ViewModel {
        }
    }
}
