//
//  HealthDetailViewController.swift
//  CleanSwiftUI
//
//  Created by Siradanai.s on 2/7/2566 BE.
//  Copyright (c) 2023. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftUI

protocol HealthDetailDisplayLogic: AnyObject {
    func displayDetail(viewModel: HealthDetail.FetchDetail.ViewModel)
}

final class HealthDetailViewController: BaseUIViewController, HealthDetailDisplayLogic {
    var interactor: HealthDetailBusinessLogic?
    var router: (HealthDetailRoutingLogic & HealthDetailDataPassing)?
    
    private let sceneViewModel = HealthDetailSceneViewModel()
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    init(recordType: HealthRecordType) {
        super.init(nibName: nil, bundle: nil)
        setupVIP(recordType: recordType)
        setupBarButton()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        interactor?.fetchDetail(request: .init())
        
        navigationItem.title = "Detail"
        
        loadMainView(
            HealthDetailMainView(
                viewProtocol: self,
                viewModel: sceneViewModel
            )
        )
    }
    
    func displayDetail(viewModel: HealthDetail.FetchDetail.ViewModel) {
        sceneViewModel.unit = viewModel.unit
        
        withAnimation {
            sceneViewModel.state = viewModel.state
        }
    }
}

extension HealthDetailViewController: HealthDetailMainViewProtocol {
    func recordDidTap(recordId: UUID) {
        router?.routeToEditData(recordId: recordId)
    }
}

private extension HealthDetailViewController {
    func setupVIP(recordType: HealthRecordType) {
        let viewController = self
        
        let presenter = HealthDetailPresenter(
            viewController: viewController
        )
        
        let interactor = HealthDetailInteractor(
            presenter: presenter,
            recordType: recordType,
            healthService: QueryService.shared
        )
        
        let router = HealthDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    func setupBarButton() {
        let addButton = UIBarButtonItem(title: "Add Data", style: .plain, target: self, action: #selector(handleTapAddData))
        
        navigationItem.rightBarButtonItem = addButton
    }
    
    @objc func handleTapAddData() {
        router?.routeToAddHealthRecord()
    }
}

extension HealthDetailViewController: HealthInputFormViewControllerDelegate {
    func didSubmitHealthInputData(
        withValue value: Double,
        date: Date,
        mode: HealthInputForm.SceneOption
    ) { 
        interactor?.submitRecord(
            request: .init(value: value, date: date, mode: mode)
        )
    }
    
    func didPressDelete(record: HealthRecord) {
        interactor?.removeDetail(request: .init(record: record))
    }
}
