//
//  HealthDetailPresenterWorker.swift
//  CleanSwiftUI
//
//  Created by Siradanai.s on 2/7/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol HealthDetailPresenterWorkerProtocol {
    func getUnit(ofType type: HealthRecordType) -> String
}

final class HealthDetailPresenterWorker: HealthDetailPresenterWorkerProtocol {
    func getUnit(ofType type: HealthRecordType) -> String {
        switch type {
        case .bodyMassIndex:
            return "BODY MASS INDEX"
        case .bodyFatPercentage:
            return "PERCENT"
        case .weight:
            return "KG"
        case .height:
            return "CM"
        }
    }
}
