//
//  HealthDetailInteractor.swift
//  CleanSwiftUI
//
//  Created by Siradanai.s on 2/7/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol HealthDetailBusinessLogic {}

protocol HealthDetailDataStore {}

final class HealthDetailInteractor: HealthDetailBusinessLogic, HealthDetailDataStore {
    var presenter: HealthDetailPresentationLogic
    private var worker: HealthDetailWorkerProtocol

    init(
        worker: HealthDetailWorkerProtocol = HealthDetailWorker(),
        presenter: HealthDetailPresentationLogic
    ) {
        self.worker = worker
        self.presenter = presenter
    }
}
