//
//  HealthDetailInteractor.swift
//  CleanSwiftUI
//
//  Created by Siradanai.s on 2/7/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol HealthDetailBusinessLogic {
    func fetchDetail(request: HealthDetail.FetchDetail.Request)
    func addDetail(request: HealthDetail.AddDetail.Request)
    func removeDetail(request: HealthDetail.RemoveDetail.Request)
}

protocol HealthDetailDataStore {
    var recordType: HealthRecordType! { get }
}

final class HealthDetailInteractor: HealthDetailBusinessLogic, HealthDetailDataStore {
    var presenter: HealthDetailPresentationLogic
    private var worker: HealthDetailWorkerProtocol
    
    private(set) var recordType: HealthRecordType!
    private let healthService: HealthServiceProtocol
    
    private var records: [HealthRecord] = []

    init(
        worker: HealthDetailWorkerProtocol = HealthDetailWorker(),
        presenter: HealthDetailPresentationLogic,
        recordType: HealthRecordType,
        healthService: HealthServiceProtocol
    ) {
        self.worker = worker
        self.presenter = presenter
        self.recordType = recordType
        self.healthService = healthService
    }
    
    func fetchDetail(request: HealthDetail.FetchDetail.Request) {
        refreshDetail(updateWithAnimation: true)
    }
    
    func addDetail(request: HealthDetail.AddDetail.Request) {
        healthService.createHealthRecord(
            id: UUID(),
            value: request.value,
            createdDate: request.date,
            type: recordType
        )
        
        refreshDetail(updateWithAnimation: true)
    }
    
    func removeDetail(request: HealthDetail.RemoveDetail.Request) {
        let recordsToDelete = records.elements(at: request.indexSet).compactMap { $0 }
        
        recordsToDelete.forEach {
            print($0.value)
            healthService.deleteHealthRecord(record: $0)
        }
        
        refreshDetail(updateWithAnimation: false)
    }
    
    func refreshDetail(updateWithAnimation: Bool) {
        let result = healthService.fetchHealthRecords(ofType: recordType)
        
        switch result {
        case let .success(records):
            self.records = records
            presenter.presentDetail(response: .init(
                recordType: recordType,
                records: records,
                updateWithAnimation: updateWithAnimation
            ))
        case .failure(_):
            // TODO: Handle error
            break
        }
    }
}
