//
//  CounterPresenter.swift
//  CleanSwiftUI
//
//  Created by Siradanai.s on 30/6/2566 BE.
//  Copyright (c) 2023. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardPresentationLogic {
    func presentCategory(response: Dashboard.FetchCategory.Response)
    func presentTapCategory(response: Dashboard.TapCategory.Response)
}

class DashboardPresenter: DashboardPresentationLogic {
    
    weak var viewController: DashboardDisplayLogic?
    var worker: CounterPresenterWorkerProtocol

    init(
        viewController: DashboardViewController,
        worker: CounterPresenterWorkerProtocol = DashboardPresenterWorker()
    ) {
        self.viewController = viewController
        self.worker = worker
    }

    func presentCategory(response: Dashboard.FetchCategory.Response) {
        viewController?.displayCategory(
            categoryItems: worker.mapCategoryRow(from: response.recentCategoryResponse)
        )
    }
    
    func presentTapCategory(response: Dashboard.TapCategory.Response) {
        viewController?.displayTapCategory(viewModel: .init(categoryType: response.categoryType))
    }
}
