//
//  CounterInteractor.swift
//  CleanSwiftUI
//
//  Created by Siradanai.s on 30/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol DashboardBusinessLogic {
    func fetchCateogory(request: Dashboard.FetchCategory.Request)
    func tapCategory(request: Dashboard.TapCategory.Request)
}

class DashboardInteractor: DashboardBusinessLogic {    
    var presenter: DashboardPresenter?

    init(presenter: DashboardPresenter) {
        self.presenter = presenter
    }
    
    func fetchCateogory(request: Dashboard.FetchCategory.Request) {
        let mockResponse: [CategoryResponse] = [
            .init(value: "84 kg", lastUpdate: Date(), type: .weight),
            .init(value: "21", lastUpdate: Date(), type: .bodyMassIndex)
        ]
        
        presenter?.presentCategory(response: .init(
            recentCategoryResponse: mockResponse
        ))
    }
    
    func tapCategory(request: Dashboard.TapCategory.Request) {
        presenter?.presentTapCategory(response: .init(categoryType: request.categoryType))
    }
}
