//
//  CounterViewController.swift
//  CleanSwiftUI
//
//  Created by Siradanai.s on 30/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftUI

protocol DashboardDisplayLogic: AnyObject {
    func displayCategory(categoryItems: [CategoryRowViewModel])
    func displayTapCategory(viewModel: Dashboard.TapCategory.ViewModel)
}

class DashboardViewController: UIViewController, DashboardDisplayLogic {
    
    private let viewModel = DashboardSceneViewModel(categoryItems: [])
    var interactor: DashboardInteractor!
    var presenter: DashboardPresenter!
    var router: DashboardRoutingLogic!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupVIP()
        navigationItem.title = "Dashboard"
        loadSwiftUIView(
            DashboardScreenSwiftUIView(
                interactor: interactor,
                viewModel: viewModel
            )
        )
        
        interactor.fetchCateogory(request: .init())
    }

    func displayCategory(categoryItems: [CategoryRowViewModel]) {
        viewModel.categoryItems = categoryItems
    }
    
    func displayTapCategory(viewModel: Dashboard.TapCategory.ViewModel) {
        router.routeToHealthDetail(type: viewModel.categoryType)
    }
}

private extension DashboardViewController {
    func setupVIP() {
        router = DashboardRouter(viewController: self)
        
        presenter = DashboardPresenter(
            viewController: self
        )
        
        interactor = DashboardInteractor(presenter: presenter)
    }
    
    func loadSwiftUIView(_ swiftUIView: some View) {
        let hostingController = UIHostingController(rootView: swiftUIView)
        
        addChild(hostingController)
        view.addSubview(hostingController.view)
        hostingController.view.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            hostingController.view.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            hostingController.view.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            hostingController.view.topAnchor.constraint(equalTo: view.topAnchor),
            hostingController.view.bottomAnchor.constraint(equalTo: view.bottomAnchor)
        ])
        hostingController.didMove(toParent: self)
    }
}

struct DashboardScreenSwiftUIView: View {
    var interactor: DashboardInteractor?
    @ObservedObject var viewModel: DashboardSceneViewModel
    
    var body: some View {
        List(viewModel.categoryItems, id: \.category) { category in
            CategoryRow(
                viewModel: category
            ).onPress {
                print("### DEBUG tap")
                interactor?.tapCategory(request: .init(categoryType: category.category))
            }
        }
    }
}

fileprivate let categoryViewModel: [CategoryRowViewModel] = [
    .init(
        title: "Weight",
        value: "84 kg",
        lastUpdated: Date().toString(),
        category: .weight
    ),
    .init(
        title: "Body Mass Index",
        value: "21",
        lastUpdated: Date().toString(),
        category: .bodyMassIndex
    ),
]

struct DashboardScreenSwiftUIView_Previews: PreviewProvider {
    static var previews: some View {
        DashboardScreenSwiftUIView(
            interactor: nil,
            viewModel: .init(categoryItems: categoryViewModel)
        )
    }
}
