//
//  CounterPresenterWorker.swift
//  CleanSwiftUI
//
//  Created by Siradanai.s on 30/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CounterPresenterWorkerProtocol {
    func mapCategoryRow(from response: [CategoryResponse]) -> [CategoryRowViewModel]
}

final class DashboardPresenterWorker: CounterPresenterWorkerProtocol {
    func mapCategoryRow(from response: [CategoryResponse]) -> [CategoryRowViewModel] {
        return response
            .filter { $0.value != nil && $0.lastUpdate != nil }
            .map { (getTitle(for: $0.type), $0.value! , $0.lastUpdate!.toString(), $0.type) }
            .map(CategoryRowViewModel.init)
    }
}



private extension DashboardPresenterWorker {
    func getTitle(for type: CategoryType) -> String {
        switch type {
        case .bodyMassIndex:
            return "Body Mass Index"
        case .bodyFatPercentage:
            return "Body Fat Percentage"
        case .weight:
            return "Weight"
        case .height:
            return "Height"
        }
    }
}
