//
//  CounterRouter.swift
//  CleanSwiftUI
//
//  Created by Siradanai.s on 30/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardRoutingLogic {
    func routeToHealthDetail(type: CategoryType)
}

final class DashboardRouter: DashboardRoutingLogic {
    weak var viewController: DashboardViewController?
    
    init(viewController: DashboardViewController?) {
        self.viewController = viewController
    }
    
    
    func routeToHealthDetail(type: CategoryType) {
        guard let navVC = viewController?.navigationController else {
            return
        }
        
        navVC.pushViewController(HealthDetailViewController(), animated: true)
    }
}
