//
//  CounterPresenterWorker.swift
//  CleanSwiftUI
//
//  Created by Siradanai.s on 30/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CounterPresenterWorkerProtocol {
    func mapCategoryRow(from response: [CategoryResponse]) -> [CategoryRowViewModel]
}

final class DashboardPresenterWorker: CounterPresenterWorkerProtocol {
    func mapCategoryRow(from response: [CategoryResponse]) -> [CategoryRowViewModel] {
        return response
            .map { (
                getTitle(for: $0.type),
                $0.value ?? "No Data" ,
                getUnitDisplay(for: $0.type, value: $0.value),
                    .init(value: $0.lastUpdate?.toString()),
                $0.type
            ) }
            .map(CategoryRowViewModel.init)
    }
}



private extension DashboardPresenterWorker {
    func getTitle(for type: HealthRecordType) -> String {
        switch type {
        case .bodyMassIndex:
            return "Body Mass Index"
        case .bodyFatPercentage:
            return "Body Fat Percentage"
        case .weight:
            return "Weight"
        case .height:
            return "Height"
        }
    }
    
    func getUnitDisplay(for type: HealthRecordType, value: String?) -> Display<String> {
        guard value != nil else { return .hidden }
        
        switch type {
        case .bodyMassIndex:
            return .hidden
        case .bodyFatPercentage:
            return .visible("%")
        case .weight:
            return .visible("KG")
        case .height:
            return .visible("cm")
        }
    }
}
