//
//  CounterModels.swift
//  CleanSwiftUI
//
//  Created by Siradanai.s on 30/6/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum Dashboard {
    enum FetchCategory {
        struct Request {}

        struct Response {
            let recentCategoryResponse: [CategoryResponse]
        }

        struct ViewModel {
            let categoryItems: [CategoryRowViewModel]
        }
    }
    
    enum TapCategory {
        struct Request {
            let categoryType: CategoryType
        }

        struct Response {
            let categoryType: CategoryType
        }

        struct ViewModel {
            let categoryType: CategoryType
        }
    }
}
