//
//  HealthInputFormPresenter.swift
//  VIPSwiftUI
//
//  Created by Siradanai.s on 7/7/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol HealthInputFormPresentationLogic {
    func presentProceedTextInput(response: HealthInputForm.ProceedTextInput.Response)
}

final class HealthInputFormPresenter: HealthInputFormPresentationLogic {
    weak var viewController: HealthInputFormDisplayLogic?
    var worker: HealthInputFormPresenterWorkerProtocol

    var controller: HealthInputFormDisplayLogic? {
        return viewController
    }

    init(
        viewController: HealthInputFormDisplayLogic,
        worker: HealthInputFormPresenterWorkerProtocol = HealthInputFormPresenterWorker()
    ) {
        self.viewController = viewController
        self.worker = worker
    }
    
    func presentProceedTextInput(response: HealthInputForm.ProceedTextInput.Response) {
        viewController?.displayProceedTextInput(viewModel: .init(addButtonEnabled: response.addButtonEnabled))
    }
}
