//
//  HealthInputFormPresenterWorker.swift
//  VIPSwiftUI
//
//  Created by Siradanai.s on 7/7/2566 BE.
//  Copyright (c) 2023. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol HealthInputFormPresenterWorkerProtocol {
    func mapUnitLabel(recordType: HealthRecordType) -> String
}

final class HealthInputFormPresenterWorker: HealthInputFormPresenterWorkerProtocol {
    func mapUnitLabel(recordType: HealthRecordType) -> String {
        switch recordType {
        case .bodyMassIndex:
            return "BMI"
        case .bodyFatPercentage:
            return "%"
        case .weight:
            return "kg"
        case .height:
            return "cm"
        }
    }
}
