//
//  HealthInputFormViewController.swift
//  VIPSwiftUI
//
//  Created by Siradanai.s on 7/7/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftUI

protocol HealthInputFormDisplayLogic: AnyObject {}

final class HealthInputFormViewController: BaseUIViewController, HealthInputFormDisplayLogic {
    var interactor: HealthInputFormBusinessLogic?
    var router: (HealthInputFormRoutingLogic & HealthInputFormDataPassing)?

    override func viewDidLoad() {
        super.viewDidLoad()
    }
}

private extension HealthInputFormViewController {
    func setupVIP() {
        let viewController = self

        let presenter = HealthInputFormPresenter(
            viewController: viewController
        )

        let interactor = HealthInputFormInteractor(
            presenter: presenter
        )

        let router = HealthInputFormRouter()
        viewController.interactor = interactor
        viewController.router = router
        router.viewController = viewController
        router.dataStore = interactor
    }
}

struct HealthInputFormView: View {
    var interactor: HealthInputFormInteractor?
    @ObservedObject var viewModel: HealthInputFormSceneViewModel
    
    var body: some View {
        List {
            HStack {
                Text("Date")
                Spacer()
                Text("\(viewModel.date)")
            }
            
            HStack {
                Text("Time")
                Spacer()
                Text("\(viewModel.date)")
            }
            
            HStack {
                Text(viewModel.unitLabel)
                Spacer()
//                TextField(<#LocalizedStringKey#>, text: <#Binding<String>#>)
            }
        }
    }
}

struct HealthInputFormView_Previews: PreviewProvider {
    static var previews: some View {
        HealthInputFormView(viewModel: sceneViewModel)
    }
}

fileprivate let sceneViewModel = HealthInputFormSceneViewModel(
    date: Date().toString(),
    time: (hour: 14, minute: 23),
    value: 84,
    unitLabel: "kg"
)




