//
//  HealthInputFormInteractor.swift
//  VIPSwiftUI
//
//  Created by Siradanai.s on 7/7/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol HealthInputFormBusinessLogic {
    var inputText: String? { get }
    var inputDate: Date? { get }
    
    func prepareData(request: HealthInputForm.PrepareData.Request)
    func proceedTextInput(request: HealthInputForm.ProceedTextInput.Request)
    func proceedDateInput(request: HealthInputForm.ProceedDateInput.Request)
}

protocol HealthInputFormDataStore {}

final class HealthInputFormInteractor: HealthInputFormBusinessLogic, HealthInputFormDataStore {
    var presenter: HealthInputFormPresentationLogic
    private var worker: HealthInputFormWorkerProtocol
    
    private let sceneOption: HealthInputForm.SceneOption
    
    private(set) var inputText: String?
    private(set) var inputDate: Date?

    init(
        worker: HealthInputFormWorkerProtocol = HealthInputFormWorker(),
        presenter: HealthInputFormPresentationLogic,
        sceneOption: HealthInputForm.SceneOption
    ) {
        self.worker = worker
        self.presenter = presenter
        self.sceneOption = sceneOption
    }
    
    func prepareData(request: HealthInputForm.PrepareData.Request) {
        switch sceneOption {
        case let .add(recordType):
            inputDate = Date()
            inputText = ""
            
            presenter.presentPreparedData(response: .init(
                date: inputDate ?? Date(),
                value: nil,
                recordType: recordType,
                addButtonEnabled: shouldButtonEnabled()
            ))
            break
        case let .edit(record):
            break
        }
    }
    
    func proceedTextInput(request: HealthInputForm.ProceedTextInput.Request) {
        inputText = request.text
        let buttonEnabled = shouldButtonEnabled()
        presenter.presentProceedTextInput(response: .init(addButtonEnabled: buttonEnabled))
    }
    
    func proceedDateInput(request: HealthInputForm.ProceedDateInput.Request) {
        inputDate = request.date
    }
    
    func shouldButtonEnabled() -> Bool {
        return inputText?.isEmpty == false && inputDate != nil
    }
}
