//
//  HealthInputFormModels.swift
//  VIPSwiftUI
//
//  Created by Siradanai.s on 7/7/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum HealthInputForm {
    
    enum SceneOption {
        case add(recordType: HealthRecordType)
        case edit(record: HealthRecord)
    }
    
    enum PrepareData {
        struct Request {}

        struct Response {
            let date: Date
            let value: Double?
            let recordType: HealthRecordType
        }

        struct ViewModel {
            let dateTitle: String
            let timeTitle: String
            let unitTitle: String
            
            let dateValue: Date
            let textValue: String
        }
    }
    
    enum ProceedTextInput {
        struct Request {
            let text: String
        }

        struct Response {
            let addButtonEnabled: Bool
        }

        struct ViewModel {
            let addButtonEnabled: Bool
        }
    }
    
    enum ProceedDateInput {
        struct Request {
            let date: Date
        }
    }
}
